### ISSUE TITLE
Chromium Wayland support for clear scaling

### ISSUE THREAD

**Issue by pothos** [nuehm-arno/axolotl-mobian-package#2]
Run electron with `--enable-features=UseOzonePlatform  --ozone-platform=wayland` once built with the Chromium ozone backend.

**Comment by nuehm-arno** [comment]
Will have a look into it and forward the issue to the Axolotl developers. Thanks for the suggestion!

**Comment by nuehm-arno** [comment]
Issue copied to the original source repo:

https://github.com/nanu-c/axolotl/issues/444

**Comment by nuehm-arno** [comment]
Resolved with v1.0.7.
