### ISSUE TITLE
Wrong version displayed in Settings>About Axolotl ?

### ISSUE THREAD

**Issue by loveisfoss** [nuehm-arno/axolotl-mobian-package#3]
Hey, thanks for your work packaging this for Mobian! I have installed v0.9.9-1 but in the Settings>About Axolotl I see Axolotl Beta 0.9.8.

**Comment by nuehm-arno** [comment]
Thanks for contributing. Updating the version tag in "About Axolotl" was simply forgotten but will be corrected upstream in v0.9.10.

Have a nice day!
