### ISSUE TITLE
Outgoing messages do not work, incoming are OK

### ISSUE THREAD

**Issue by dukla2000** [nuehm-arno/axolotl-mobian-package#4]
I had this problem with previous version and now with v1.0 and have not been able to cure it. In short my Axolotl seems unable to get anything back to the Signal servers (outgoing messages, even confirmations that I have read messages) but can receive incoming messages fine.
I attach a log from Mobian of a fresh install. I have redacted some digits in my phone number and some characters in contact names. The log includes the initial setup (including Captcha), then I add 3 contacts, then at around 16:17:16 I receive a message in a group. Then I try to send a response that (an hour later) I still only have 1 tick for in my Axolotl.
[axolotl.log](https://github.com/nuehm-arno/axolotl-mobian-package/files/6562002/axolotl.log)

**Comment by nuehm-arno** [comment]
Copied to upstream

https://github.com/nanu-c/axolotl/issues/504
