### ISSUE TITLE
Linking Devices works only for one Device

### ISSUE THREAD

**Issue by magdesign** [nuehm-arno/axolotl-mobian-package#5]
Installed latest version on mobian pinephone (Beta 1.0.0) today.

I was able to link one of my computers, but its not possible to link a second one,
when clicking on the "Linked Devices" button, only a white screen appears.

**Comment by nuehm-arno** [comment]
Hi and thanks for openening this issue. I will forward this to the Axolotl Github repo and post the link here.

And yes, it is a known issue.

And sorry for the late response - I was on holidays.

**Comment by nuehm-arno** [comment]
https://github.com/nanu-c/axolotl/issues/529

**Comment by chookity-pokk** [comment]
This is late so you might now see it, but @magdesign, how did you manage linking the device? I tried with my desktop but it says to copy in what the QR code says into Axolotl and the text from the QR code was so long that I couldn't fit it all in one screen.

**Comment by magdesign** [comment]
I plugged in an usb mouse to select the code, used the terminal keyboard to type ctrl+c and then pasted it in axolotl.
Maybe even selecting with mouse and paste it with middle click should work.

**Comment by chookity-pokk** [comment]
Shoot, I don't have a dock so I can't really do this. I appreciate the response though.

**Comment by chookity-pokk** [comment]
I just tried this and couldn't connect to a single device. Did it take a while for you to connect? When I submit the QR code data the dialog box just disappears and nothing happens.

**Comment by magdesign** [comment]
> Shoot, I don't have a dock so I can't really do this. I appreciate the response though.

use the terminal keyboard to "CTRL+C" and "CTRL+V"

**Comment by magdesign** [comment]
> I just tried this and couldn't connect to a single device. Did it take a while for you to connect? When I submit the QR code data the dialog box just disappears and nothing happens.

It takes a while and sometimes you need to do 2 attempts. Remember to give the ok on the device you want to connect.

**Comment by nuehm-arno** [comment]
Should be resolved with v1.0.5... Please confirm and let close the issue in the official repo.
