### ISSUE TITLE
Contacts can not be deleted/edited

### ISSUE THREAD

**Issue by magdesign** [nuehm-arno/axolotl-mobian-package#6]
After adding a contact its not possible to correct/change/delete the entry.

**Comment by nuehm-arno** [comment]
Thanks again for opening this issue. It is again known and is due to a deprecated long-press tap function, which will be back soon.
I will transfer this issue to the Axolotl Github repo, too.
Cheers!

**Comment by nuehm-arno** [comment]
https://github.com/nanu-c/axolotl/issues/530

**Comment by nuehm-arno** [comment]
You can always edit or delete contacts using an editor on these files
`~/.config/textsecure.nanuc/contacts.yml`
`~/.config/textsecure.nanuc/registeredContacts.yml`

**Comment by magdesign** [comment]
perfect, thanks for the workaround!

**Comment by nuehm-arno** [comment]
Should be resolved with v1.0.5... Please confirm and let me close the issue in the official repo.
